include:
  - proxy.yaml
services:
  web:
    depends_on: ["db"]
    image: cr.yandex/crp9h0r7pj94tg9t9jnp/c3pocube/web-python:1.0.0
    environment:
      - DB_HOST=172.20.0.10
      - DB_USER=app
      - DB_PASSWORD=QwErTy1234
      - DB_NAME=virtd
    ports:
      - "5000:5000"
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.5
  db:
    image: mysql:8
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql/
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10
  cron:
    image: schnitzler/mysqldump
    restart: always
    volumes:
      - ./bin/crontab:/var/spool/cron/crontabs/root
      - ./bin/backup:/usr/local/bin/backup
    volumes_from:
      - backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: 172.20.0.10
      MYSQL_USER: app
      MYSQL_PASSWORD: QwErTy1234
      MYSQL_DATABASE: virtd
    networks:
      backend:
        ipv4_address: 172.20.0.15
  backup:
    image: busybox
    volumes:
      - /opt/backup:/backup
    networks:
      backend:
        ipv4_address: 172.20.0.20
